name: JavaScript Demo
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: itgoyo/javascript-action@master
        env:
         ftkey: ${{ secrets.FT_API_KEY }}

